name = "GNBC"
uuid = "f3330e14-0c7f-43fd-a4a7-c99c2bc4bebe"
authors = ["Daymond Ling"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
